version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      time: "01:00"
    ignore:
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: weekly
  
  - package-ecosystem: "docker"
    directory: "/.devcontainer"
    schedule:
      interval: weekly
